package grpc

import (
	"context"

	v1 "app-hexagonal/api/v1"
	"app-hexagonal/internal/application"
	"app-hexagonal/internal/domain"

	"go.uber.org/zap"
	"google.golang.org/grpc/codes"
)

// UserServiceServer implements the UserService gRPC service
type UserServiceServer struct {
	v1.UnimplementedUserServiceServer
	userService *application.UserService
	logger      *zap.Logger
}

// NewUserServiceServer creates a new UserServiceServer
func NewUserServiceServer(userService *application.UserService, logger *zap.Logger) *UserServiceServer {
	return &UserServiceServer{
		userService: userService,
		logger:      logger,
	}
}

// GetUser retrieves a user by ID
func (s *UserServiceServer) GetUser(ctx context.Context, req *v1.GetUserRequest) (*v1.GetUserResponse, error) {
	s.logger.Info("gRPC: Getting user by ID", zap.String("user_id", req.GetId()))

	user, err := s.userService.GetUserByID(req.GetId())
	if err != nil {
		s.logger.Error("gRPC: Failed to get user", zap.String("user_id", req.GetId()), zap.Error(err))
		return &v1.GetUserResponse{
			Error:   true,
			Code:    int32(codes.NotFound),
			Message: "User not found",
		}, nil
	}

	// Convert domain user to protobuf user
	protoUser := &v1.User{
		Id:    user.ID,
		Name:  user.Name,
		Email: user.Email,
	}

	s.logger.Info("gRPC: Successfully retrieved user", zap.String("user_id", user.ID))

	return &v1.GetUserResponse{
		Error:   false,
		Code:    int32(codes.OK),
		Message: "User retrieved successfully",
		Data:    protoUser,
	}, nil
}

// CreateUser creates a new user
func (s *UserServiceServer) CreateUser(ctx context.Context, req *v1.CreateUserRequest) (*v1.CreateUserResponse, error) {
	s.logger.Info("gRPC: Creating new user", zap.String("user_name", req.GetName()), zap.String("user_email", req.GetEmail()))

	// Create domain user
	user := &domain.User{
		ID:    "", // ID will be generated by the repository
		Name:  req.GetName(),
		Email: req.GetEmail(),
	}

	// Save user
	err := s.userService.CreateUser(user)
	if err != nil {
		s.logger.Error("gRPC: Failed to create user", zap.Error(err))
		return &v1.CreateUserResponse{
			Error:   true,
			Code:    int32(codes.Internal),
			Message: "Failed to create user",
		}, nil
	}

	// Convert domain user to protobuf user
	protoUser := &v1.User{
		Id:    user.ID,
		Name:  user.Name,
		Email: user.Email,
	}

	s.logger.Info("gRPC: User created successfully", zap.String("user_id", user.ID))

	return &v1.CreateUserResponse{
		Error:   false,
		Code:    int32(codes.OK),
		Message: "User created successfully",
		Data:    protoUser,
	}, nil
}
